version: '3'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: desafio_back_end_brisalabs_app
    restart: always
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/home/node/app
    depends_on:
      - db_postgresql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - backend

  db_postgresql:
    build: .docker/postgres
    container_name: desafio_back_end_brisalabs_db
    restart: always
    tty: true
    volumes: 
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:5432
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
